import Head from "next/head";
import Link from "next/link";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.grid}>
        <Link href="/map" className={styles.card}>
          <h2 className={inter.className}>
            Map <span>-&gt;</span>
          </h2>
          <p className={inter.className}>Find the bus stop from the map.</p>
        </Link>
      </div>
    </>
  );
}
